### ISSUE TITLE
Reset button glitch #2 

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#330]
location : all levels
description : spam clicking the reset button cuts down the animation to less than half a second. after which just clicking the reset button once the animation plays for half a second like it did when spam clicked.
the time u take in between each reset click is the time the animation plays. so if i click the reset button every 1 sec , 
the animation plays for one sec and cuts out , if clicked half a second , animations plays for half a second a cuts.

**Comment by SilasReinagel** [comment]
Technical Notes: We should disable to ability to spam click any button.
