### ISSUE TITLE
missing punctuations 

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#332]
The dialogue boxes have missing fullstops at the end of sentences. also certain dialogues are missing coma's so get a writer to revise over it

**Comment by SilasReinagel** [comment]
This issue has no context, and doesn't report any particular typo.

Also, there are 5 existing tickets for reviewing the writing, so the general suggestion is a duplicate.

We can only accept report of specific typos in specific sentences.
