### ISSUE TITLE
Level Select on Slade Server is broken

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#372]
When selecting a level in the slades server via level select , levels 1 onwards do not show the story. they skip directly to the level.

**Comment by SilasReinagel** [comment]
Which version is this on? 

I cannot reproduce this issue. I'm wondering if you are playing a version before Zone 5 story was put into the game.

**Comment by SilasReinagel** [comment]
This bug is from old version 0.7.1.

That version did not have the story for Zone 5.
