### ISSUE TITLE
Home Ui suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#412]
Have a tablet like the player is holding instead of just having the options , shorten the game title a little and move it up so the tablet is bigger and nothing looks cramped. have a box highlighted when the mouse hovers over one of the selection options like play.

**Comment by SilasReinagel** [comment]
I don't understand this suggestion. Can you highlight elements on a screenshot?

**Comment by SilasReinagel** [comment]
Duplicate of EnigmaDragons/ProjectBitVault#414
