### ISSUE TITLE
HomeScreen UI suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#414]
![image](https://user-images.githubusercontent.com/56066524/71764605-d6488500-2efa-11ea-8385-802431a3ee2e.png)
This is a rough sketch of my idea
so you have the tablet like the ones the players are holding
And you have the text on that
the different menu options
and when the cursor is put on top of an option it highlights it
work and play around the UI a little

**Comment by SilasReinagel** [comment]
This is a cool idea, but will cost too much developer budget, and won't port well to mobile. 

We might try something like this in a future game.
