### ISSUE TITLE
story sequence issue (bug)

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#468]
the 2nd story is the same as the 3rd and 4th level story .
ie , "the next servers should be easy too..."

**Comment by mustucontractor** [comment]
I think all the rest of the story sequence has been pushed later so level 3 story is being played on level 5 and so on

**Comment by SilasReinagel** [comment]
@mustucontractor Did check the story after completing each level? Or are you just seeing the same story section if you start three levels without playing them?
