### ISSUE TITLE
skip feature suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#469]
No point in having skip story as an option in the settings , having a custom puzzle only and story mode feature in new game and having a skip option during the story dialogues , keep it simple and remove the story mode and puzzle only option and have story mode default , if players don't want the story they can skip it from the options.

**Comment by SilasReinagel** [comment]
The feature is needed if they change their mind mid-way through the story. 

It's very important to have both, based on our easy user playtesting sessions.
