### ISSUE TITLE
Blur issue (Screenshot)

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#616]
Everything is blurry and not clear for some reason.
![image](https://user-images.githubusercontent.com/56066524/74583547-19594600-4fd9-11ea-8f57-72ef29ec3fe6.png)

**Comment by SilasReinagel** [comment]
Having a hard time re-producing this. 

Can you add the version number and your computer specs?

**Comment by mustucontractor** [comment]
0.7.6

Computer specs are
12Gb Ram 
core I7 9th gen
GeForce gtx 860 (I think , something in the 800's)

**Comment by SilasReinagel** [comment]
Probably related to Unity scaling. I can reproduce this issue in windowed mode on my home pc.

This is a possible solution: https://answers.unity.com/questions/1226551/ui-text-is-blurred-unity-535f.html?_ga=2.223166299.1594397951.1585363175-183739658.1568098069
