### ISSUE TITLE
Credits scene name mistake

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#620]
My name should be in the box below and Tester should be written above
![image](https://user-images.githubusercontent.com/56066524/74583686-a8b32900-4fda-11ea-83f7-9ba818b62aa5.png)

**Comment by SilasReinagel** [comment]
This bug was reported from an old version. This is already fixed in the beta.

![image.png](https://zube.io/files/enigmadragons/55f887510b9a6125e399c0b004159136-image.png)
