### ISSUE TITLE
Exit option suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#623]
Dont have 'exit game' as an option while playing a level. any exit option should be only in the main menu

**Comment by SilasReinagel** [comment]
Can you explain more about the reasoning for this?

**Comment by mustucontractor** [comment]
It seems kinda cleaner and more organized that way. so once players are done with the level they go to main menu and then click exit. Its how its done with most games. It just looks more professional and clean in my opinion

**Comment by SilasReinagel** [comment]
Desktop Users want all the controls. For Desktop users, we will keep this button. 

It doesn't exist for Mobile/Web presently.
