### ISSUE TITLE
Bg feature suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#624]
Just like how the loading screen is there , add a couple more such images and have a feature where players can select their backgrounds. for eg : have backgrounds purchasable with cubes u collect 
make 2 versions of them
cheap one- the current background In game but with different theme colors like neon pink , orange etc
avg one - have these custom detailed images made , around 3 should be good

players can select and change their background. This adds another reason for the to keep playing the game and trying to collect more data cubes and stuff.
You can also reward them with a few Bg's after a certain set of levels are completed.

**Comment by SilasReinagel** [comment]
We'll decide on this one once we decide on whether to add more rewards into the game.

**Comment by SilasReinagel** [comment]
We're killing off rewards for now.
