### ISSUE TITLE
Font change suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#625]
Not a huge fan of this font , since it is a hacking game , a more modern font would stand out.. this one gives a really cartoony/ kids game effect.

![image](https://user-images.githubusercontent.com/56066524/74583844-aeaa0980-4fdc-11ea-8dd8-d0ec370d0b81.png)

**Comment by SilasReinagel** [comment]
This is considering a science-fiction font. I think we'll stick with it.
