### ISSUE TITLE
loading screen issue

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#626]
Since the game is light and there is barely any loading time , it always flashes a 100%. rather than this just don't show any percentage , just have it say 'loading' 

![image](https://user-images.githubusercontent.com/56066524/74583908-73f4a100-4fdd-11ea-8e48-8f778f278216.png)

**Comment by SilasReinagel** [comment]
Loading screens are not in the current version of the beta. If we put them back in, we can consider this.
