### ISSUE TITLE
Piece didn't update to reflect move after game idled ~12 hours (screenshopt, video)

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/ProjectBitVault#629]
The screenshot shows the piece I had moved, and based on the hints, it really does think the piece was moved.

![2020-02-18_06h47_46.png](https://zube.io/files/enigmadragons/10b67b181b320a28cafed2312e653e29-2020-02-18_06h47_46.png)

The video shows that the piece is selectable, but clearly the hints suggest the game believes the piece is in a different place.

[game-display-failed-to-reflect-move.zip](https://zube.io/files/enigmadragons/d0eb4a42f6a909d3f2c2fb66a6babba6-game-display-failed-to-reflect-move.zip)

I was able to solve the puzzle (for 2 cubes), so the game worked as if the piece was there.

Since the game had been idling so long, I'm not sure if I had been using the "back" button, but there is a good chance I had used it at least once on the red pieces, but probably not on the (believed-to-be-broken) purple pieces.

**Comment by SilasReinagel** [comment]
We have tried hard to reproduce this, and unable to reproduce this issue.
